CREATE TABLE IF NOT EXISTS LOGS
   (USER_ID VARCHAR(20) NOT NULL,
    PIE VARCHAR(20),
    DATE   TIMESTAMP NOT NULL,
    LOGGER  VARCHAR(50) NOT NULL,
    LEVEL   VARCHAR(10) NOT NULL,
    MESSAGE TEXT,
    STACKTRACE TEXT
   );